# -*- coding: utf-8 -*-
"""Bryce S Lab 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19cwRKXSnp-_RTSRQRrAOE6iedev-lmNZ
"""

board = []

def print_board():
  for i in range(3):
    row = []
    for j in range(3):
        row.append('-')
    print(row)
  

print_board()