# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19cwRKXSnp-_RTSRQRrAOE6iedev-lmNZ
"""

for i in range(3):
  row = []
  for j in range(3):
      row.append('-')
  print(row)