# -*- coding: utf-8 -*-
"""Bryce S Part 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRV08aN2QZ66BBIwHTEMCylMSOkvwj21
"""

import random


def start_player():
  player = random.randint(0, 1)
  return player

starter = start_player
if starter == 0:
  player_one = "X"
  player_two = "O"

while game_continue() == True:
  row = input("Enter row number for move: ")
  col = input("Enter column number for move: ")
  board[row, col] = player_one
  
  
def game_continue():
  for i in range(n):
    for j in range(n):
        if board[i][j] != player:
            return False
            break
    else:
      return True

    for i in range(n):
        for j in range(n):
            if board[j][i] != player:
                return False
                break
        else: 
          return True


print(row, col)